"""
Django settings for tartanilla_admin project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-l_21n+x(07zszk%74-9yakq7j(41&oz#62g)!aauittxkmzkx2')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['*'] if DEBUG else ['.onrender.com', 'tartanilla-admin.onrender.com', 'localhost', '127.0.0.1']

# Network timeout settings - Reduced for faster response
CONN_MAX_AGE = 30  # Database connection timeout
SOCKET_TIMEOUT = 15  # Socket timeout
REQUEST_TIMEOUT = 15  # Request timeout

# WSGI server settings
WSGI_TIMEOUT = 30
WSGI_KEEPALIVE = 2


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',  # Required for DRF browsable API
    'django.contrib.auth',  
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Core optimization modules
    'core',
    
    # Application modules
    'accounts',
    'chat',
    'chatsupport',
    'rest_framework',
    'tourpackage',
    'api',
    'corsheaders',
    'routemanagement',
    'earningsAndshares',
    'auditlogs',
    'tartanillacarriages',
    'announcements',
    'reports'
]

MIDDLEWARE = [
    'core.connection_header_middleware.RemoveConnectionHeaderMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Add CORS settings after MIDDLEWARE
CORS_ALLOW_ALL_ORIGINS = True  # For development only
CORS_ALLOW_CREDENTIALS = True
CORS_PREFLIGHT_MAX_AGE = 86400

# Enhanced CSRF settings
CSRF_COOKIE_SECURE = not DEBUG  # Secure in production
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_NAME = 'tartanilla_csrftoken'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://d8f2a57bd131.ngrok-free.app",
]

# Exempt API endpoints from CSRF (mobile apps don't use CSRF tokens)
CSRF_EXEMPT_URLS = [
    r'^/api/',  # All API endpoints
]

# Enhanced security settings
SECURE_CONTENT_TYPE_NOSNIFF = False  # Disabled to fix JSON encoding
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# Production security settings (enable when deploying)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    # Development HTTPS enforcement for testing
    SECURE_SSL_REDIRECT = False
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8081",  # Expo development server
    "http://127.0.0.1:8081",
    "http://localhost:19006",  # Expo web
    "http://127.0.0.1:19006",
    "exp://localhost:19000",   # Expo development
    "exp://127.0.0.1:19000",
    "http://192.168.1.9:8000",  # Current Django server IP
    "http://192.168.1.9:8081",  # Expo dev server on current IP
    "exp://192.168.1.9:19000",  # Expo development on current IP
    "http://192.168.101.80:8000",  # Your local IP for mobile access
    "http://192.168.101.80:8081",  # Expo dev server on local IP
    "exp://192.168.101.80:19000",  # Expo development on local IP
    "https://d8f2a57bd131.ngrok-free.app",  # Current ngrok URL
    "https://*.ngrok-free.app",  # Allow any ngrok subdomain
    "https://*.ngrok.io",  # Allow ngrok.io domains
]

# Additional CORS headers for mobile apps
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cache-control',
    'pragma',
    'ngrok-skip-browser-warning',  # Required for ngrok
    'x-forwarded-for',
    'x-forwarded-proto',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Add timeout and buffer settings for Django
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
DATA_UPLOAD_TIMEOUT = 60  # 60 seconds
FILE_UPLOAD_TIMEOUT = 60  # 60 seconds

# Fix response truncation issues
SERVER_EMAIL_TIMEOUT = 60
EMAIL_TIMEOUT = 60

# Prevent response buffering/truncation
STREAMING_CONTENT_TYPES = []
FORCE_SCRIPT_NAME = None
USE_ETAGS = False

# Development server settings
if DEBUG:
    import sys
    import os
    # Force unbuffered output to prevent JSON truncation
    os.environ['PYTHONUNBUFFERED'] = '1'
    # Increase buffer sizes
    sys.stdout.reconfigure(line_buffering=False)
    
# Fix JSON response truncation
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB

# HTTP response settings
HTTP_RESPONSE_TIMEOUT = 60
HTTP_KEEP_ALIVE_TIMEOUT = 60

# Add REST Framework settings with timeout
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # Add this for browsable API
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/minute',
        'user': '1000/minute'
    },
}

ROOT_URLCONF = 'tartanilla_admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',  # Add this back
                'django.contrib.messages.context_processors.messages',
                
                'accounts.context_processors.user_data',
            ],
        },
    },
]

WSGI_APPLICATION = 'tartanilla_admin.wsgi.application'



import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_ANON_KEY = os.getenv("SUPABASE_ANON_KEY")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")

# Logging configuration for better error tracking
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'api': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'tartanilla_admin.supabase': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
#
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy'
    }
}

# Cache configuration for performance optimization
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'tartanilla-cache',
        'TIMEOUT': 300,  # 5 minutes default timeout
        'OPTIONS': {
            'MAX_ENTRIES': 50000,  # Increased for all modules
            'CULL_FREQUENCY': 3,
        }
    }
}

# Cache configuration for different environments
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 300
CACHE_MIDDLEWARE_KEY_PREFIX = 'tartanilla'
# Make sure to set SUPABASE_DB_NAME, SUPABASE_DB_USER, SUPABASE_DB_PASSWORD, SUPABASE_DB_HOST, and SUPABASE_DB_PORT in your environment variables.

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Remove AUTH_PASSWORD_VALIDATORS


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL is the URL to use when referring to static files located in STATIC_ROOT.
# STATIC_ROOT is the absolute path to the directory where static files will be collected.
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [BASE_DIR / 'static']

# Add WhiteNoise for static file serving in production
if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# URL Configuration
APPEND_SLASH = True

# Store sessions in signed cookies to avoid database dependency
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

# Enhanced Session Configuration
SESSION_COOKIE_AGE = 7 * 24 * 60 * 60  # 7 days in seconds (604800 seconds)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Don't expire when browser closes
SESSION_SAVE_EVERY_REQUEST = True  # Refresh session on every request
SESSION_COOKIE_SECURE = not DEBUG  # Secure in production
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
SESSION_COOKIE_NAME = 'tartanilla_sessionid'  # Custom session cookie name

# Store messages in cookies to avoid session writes
MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'

# PayMongo Payment Gateway Configuration
# Environment variables already loaded above

# PayMongo API Keys (use environment variables in production)
PAYMONGO_SECRET_KEY = os.getenv('PAYMONGO_SECRET_KEY', 'sk_test_your_secret_key_here')
PAYMONGO_PUBLIC_KEY = os.getenv('PAYMONGO_PUBLIC_KEY', 'pk_test_your_public_key_here')
PAYMONGO_WEBHOOK_SECRET = os.getenv('PAYMONGO_WEBHOOK_SECRET', 'whsec_your_webhook_secret_here')

# Payment Configuration
PAYMENT_CURRENCY = 'PHP'
PAYMENT_METHODS = ['gcash', 'grab_pay', 'paymaya', 'card']

# Twilio SMS Configuration
# Configure these in your .env file for production
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER')

# Debug Twilio configuration
if DEBUG:
    print(f"Twilio SID: {TWILIO_ACCOUNT_SID[:10] if TWILIO_ACCOUNT_SID else 'None'}...")
    print(f"Twilio Token: {TWILIO_AUTH_TOKEN[:10] if TWILIO_AUTH_TOKEN else 'None'}...")
    print(f"Twilio Phone: {TWILIO_PHONE_NUMBER}")
    print(f"Twilio configured: {bool(TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN and TWILIO_PHONE_NUMBER)}")

# Initialize connection health monitoring
try:
    from core.startup_health_monitor import initialize_health_monitoring
    initialize_health_monitoring()
except ImportError:
    print("Connection health monitoring not available")
