"""
Django settings for tartanilla_admin project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l_21n+x(07zszk%74-9yakq7j(41&oz#62g)!aauittxkmzkx2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',  # Required for DRF browsable API
    'django.contrib.auth',  
    'django.contrib.contenttypes',
    'django.contrib.sessions',  # Add this back
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'accounts',
    'chat',
    'rest_framework',
    'tourpackage',
    'api',
    'corsheaders',
    'routemanagement',
    'earningsAndshares',
    'auditlogs',
    'tartanillacarriages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tartanilla_admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tartanilla_admin.wsgi.application'



import os
from dotenv import load_dotenv
load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_ANON_KEY = os.getenv("SUPABASE_ANON_KEY")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
#
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy'
    }
}
# Make sure to set SUPABASE_DB_NAME, SUPABASE_DB_USER, SUPABASE_DB_PASSWORD, SUPABASE_DB_HOST, and SUPABASE_DB_PORT in your environment variables.

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Remove AUTH_PASSWORD_VALIDATORS


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL is the URL to use when referring to static files located in STATIC_ROOT.
# STATIC_ROOT is the absolute path to the directory where static files will be collected.
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Use cookie-based message storage since sessions are not used
MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'
